/**
 * uri-component-library
 * 
 * --scripts--
 * 
 * @version v5.0.0
 * @author Brandon Fuller <bjcfuller@uri.edu>
 * @author John Pennypacker <jpennypacker@uri.edu>
 * @license GPL-3.0
 * @see https://www.uri.edu/styleguide
 */

!function(){"use strict";const e={gid:"1bYlIQJiL4r8B0kudD_kXqzo-fgKs6ZRl6RyZjL9eRnA",dom:{output:document.getElementById("output")}};function t(e){e.classList.toggle("refresh-open")}function n(t,n,s){const a=function(t){let n,s=!0,a=0;const i=e.data[t].length;for(;s&&a<i;){s=!1,a++,n=e.data[t][Math.floor(Math.random()*i)];for(let t=0;t<e.unique.length;t++)if(n.name==e.unique[t].name){s=!0;break}}return n}(s.time);e.unique.push(a),console.log("returned",a.name)}function s(e){const s=document.createElement("li");s.classList="meal-item";const a=document.createElement("div");a.className="item-descriptors",s.appendChild(a);const i=document.createElement("div");switch(i.className="item-time "+e.time,e.time){case"short":i.innerHTML="Under 30 minutes";break;case"medium":i.innerHTML="30 - 60 minutes";break;case"long":i.innerHTML="Over 60 minutes";break;default:i.innerHTML="Time not available"}a.appendChild(i);const l=document.createElement("h2");l.className="item-name",l.innerHTML=e.name,a.appendChild(l);const c=document.createElement("div");c.className="item-ingredients",c.innerHTML=e.ingredients,a.appendChild(c);const o=document.createElement("div");o.className="item-refresh",o.innerHTML='<span class="refresh-icon">R</span>';const r=document.createElement("ul");r.className="refresh-menu";const d=[{text:"Any time",class:"refresh-any-time",time:"all"},{text:"Under 30 minutes",class:"refresh-30",time:"short"},{text:"30 - 60 minutes",class:"refresh-30-60",time:"medium"},{text:"Over 60 minutes",class:"refresh-60",time:"long"}];for(let t=0;t<d.length;t++){const a=document.createElement("li");a.className=d[t].class,a.innerHTML=d[t].text,a.addEventListener("click",n.bind(null,s,e,d[t]),!1),r.appendChild(a)}return o.appendChild(r),o.addEventListener("click",t.bind(null,s),!1),s.appendChild(o),s}window.addEventListener("load",function(t){const n=new XMLHttpRequest;n.onreadystatechange=function(){n.readyState==XMLHttpRequest.DONE&&200==n.status?t(n.responseText):0!==n.status&&n.status};const s="https://spreadsheets.google.com/feeds/list/"+e.gid+"/default/public/values?alt=json";n.open("GET",s,!0),n.send()}((function(t){const n=JSON.parse(t).feed.entry;e.data={all:[],short:[],medium:[],long:[]};let a={};for(let t=0;t<n.length;t++){a={};for(const e in n[t])e.includes("gsx$")&&(a[e.replace("gsx$","")]=n[t][e].$t);e.data.all.push(a),""!==a.time&&e.data[a.time].push(a)}!function(){e.unique=function(t){const n=e.data.all.slice(e.data.all),s=[];for(let e=0;e<t;e++){const e=Math.floor(Math.random()*n.length),t=n.splice(e,1);s.push(t[0])}return s}(14);const t=document.createElement("ul");t.className="meal-list";for(let n=0;n<e.unique.length;n++)t.appendChild(s(e.unique[n]));e.dom.output.appendChild(t)}()})),!1)}();